[bot]

# The bot's API token. Keep this secret!
token = "your-bot-token-here"

# List of owners by user ID
owners = ["130012001236811776", "145718212552687616"]

# Bot command prefix
prefix = "!"

# The tracebacks of any unexpected errors are uploaded to this file.
# Set to "0" to disable
error-channel-id = "0" 

# Path to the RDBMS futaba will use
[database]
url = "postgres://futaba:passwordhere@localhost"
