language: python

stages:
  - black
  - test

python:
  - '3.9'

jobs:
  include:
    - stage: black
      python: '3.9'
      script:
        - black --version
        - black --check --line-length 120 futaba
  fast_finish: true

cache: pip

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - flake8 --max-line-length=120 futaba

notifications:
  email:
    on_success: never
    on_failure: always